title: T and J Cleaning Services. Bradford and District.
email: admin@tandjcleaning.co.uk
description: Carpet Cleaning Specialists for Bradford and surrounding districts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - octopress-minify-html

sass:
  sass_dir: _sass
  style: compressed
